apiVersion: apps/v1
kind: Deployment
metadata:
  name: hot-rod
spec:
  selector:
    matchLabels:
      app: hot-rod
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: hot-rod
    spec:
      containers:
      - name: hot-rod
        image:  jaegertracing/example-hotrod:latest
        ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 6831
            protocol: UDP

        env:
          - name: JAEGER_AGENT_HOST
            value: "jaeger-agent.default.svc.cluster.local"
          - name: JAEGER_AGENT_PORT
            value: "6831"
---       
apiVersion: v1
kind: Service
metadata: 
  name: hot-rod
spec:    
  ports:
  - port: 8080
    name: port8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30010
  selector: 
    app: hot-rod
  type: LoadBalancer